### ISSUE TITLE
Improve the declaration of events

### ISSUE THREAD

**Issue by clearloop** [zink-lang/zink#255]
### Describe the feature

we currently only have a baseline event implementation, gather events as an enum, rich and dynamic `log{1,2,3,4}`

### Solution

```rust
#[derive(Event)]
enum Event {
  Transfer { from: Address, to: Address, value: U256 },
}
```

ABIs are also required

**Comment by malik672** [comment]
@clearloop assign me

**Comment by malik672** [comment]
@clearloop i don't really get this, are events not based on the contract

**Comment by clearloop** [comment]
> @clearloop i don't really get this, are events not based on the contract

Oh sorry, we haven't had the contract namespace yet, so an Event derive macro is enough!

For what you are confusing about, the answer is partially yes but not useful... with the benefits of rust module system we can import events from other zink contract ^ ^
